language: python
python:
  - "3.6"
  - "3.5"
env:
  - DJANGO="master"
  - DJANGO="21"
  - DJANGO="20"
  - DJANGO="111"
matrix:
  fast_finish: true
  include:
    - python: "3.4"
      env: DJANGO="111"
    - python: "2.7"
      env: DJANGO="111"
  allow_failures:
    - env: DJANGO="master"
install:
  - pip install --upgrade pip setuptools tox
script:
  - tox -e py$(python -c 'import sys;print("{0}{1}".format(*sys.version_info))')-dj${DJANGO}
notifications:
  irc: "irc.freenode.org#mezzanine"
  on_success: change
  on_failure: change
